### ISSUE TITLE
single cache invalidation

### ISSUE THREAD

**Issue by sirwolfgang** [mhgbrown/cached_resource#16]
Would be nice to have a way to call clear_cache on an instance, and have it clear the cache for that instance. That way the next time it is loaded, it will force a reload, rather then being reloaded now if don't need it.

**Comment by mhgbrown** [comment]
Fixed by https://github.com/mhgbrown/cached_resource/pull/49

**Comment by mhgbrown** [comment]
https://rubygems.org/gems/cached_resource/versions/5.2.0
