### ISSUE TITLE
Disable cached_resource in tests

### ISSUE THREAD

**Issue by plotti** [mhgbrown/cached_resource#17]
I am doing my tests with VCR i am wondering if i should/could disable cached resource in tests so i can continue to use VCR. It does not make sense to use both. Any ideas?

**Comment by Daniel-ltw** [comment]
MyActiveResource.cached_resource.off!

Would that be a temporary fix?

**Comment by jlurena** [comment]
Tests were updated 😄

**Comment by mhgbrown** [comment]
Thanks for combing through these @jlurena
