### ISSUE TITLE
:race_condition_ttl has no effect

### ISSUE THREAD

**Issue by meismann** [mhgbrown/cached_resource#19]
The abstract class `ActiveSupport::Cache::Store` prescribes several options, one of which is `race_condition_ttl`. However, when calling
```ruby
cached_resource cache: Activesupport::Cache::MemoryStore.new(race_condition_ttl: 10)
```
in class context, that option remains without effect. This is because the underlying cache does not know about a resource of the same kind is about to be retrieved already, and therefore fires a new request as soon as somebody tries to pull the resource from the cache again. This can be prevented by using `ActiveSupport::Cache::Store#fetch` instead of `#write`. `#write` cannot yield.

In general I do not think it to be a good idea to take the decision "to reload or not to reload" away from the underlying cache object and implement the decision making yourself with `#read` and `#write`. I am preparing a PR to fix the said deficiency, implementing the usage of `#fetch`. Please, let me know what you think.

**Comment by Daniel-ltw** [comment]
Implemented and put in place on version 4.2
