### ISSUE TITLE
Support for Ruby 2.2.0 and Rails 5

### ISSUE THREAD

**Issue by Daniel-ltw** [mhgbrown/cached_resource#21]
Just a curious question, would there be support for that with this gem?

**Comment by mhgbrown** [comment]
I'd hope so!  I have been a bit busy lately, but I'd like to make it compatible with both.  It might already be ok with Ruby 2.2.0, but I haven't tried it yet. Have you had any experience with this gem and Ruby 2.2.0/Rails 5?

**Comment by Daniel-ltw** [comment]
Not at the moment. 

We are thinking of moving one of our projects onto Ruby 2.2.0 and Rails 5. 
Just wondering if anyone has any experience with it.

**Comment by Daniel-ltw** [comment]
Support for Ruby 2.2.3 added in travis test.
 
Have not put in test on activeresource 4. 

Will have to do that soon, as the masses should be adopting the use of activeresource 4.

**Comment by mhgbrown** [comment]
Finally done!
https://rubygems.org/gems/cached_resource/versions/5.0.0
