### ISSUE TITLE
singleton can't be dumped

### ISSUE THREAD

**Issue by pardeepdhingra-zz** [mhgbrown/cached_resource#23]
Using [cached_resource](https://github.com/Ahsizara/cached_resource) gem for caching active resources. 

**User model**

```
class User < ActiveResource::Base
  cached_resource

  class teachers < SimpleDelegator
    attr_accessor :teacher_id

    def initialize(attributes = {}, _persisted = true)
      @teacher_id = attributes['teacher_id']
      super(User.find(@teacher_id))
    end
  end
end
```

I am trying to cache user resources. 

`/users/:user_id`

Whenever i am calling /users/:user_id endpoint it gives me error singleton can't be dumped at line `super(User.find(@teacher_id))`

Please let me know if any other info is required. I am stucked with it, please help me out.

**Comment by mhgbrown** [comment]
I am wondering if maybe you are encountering something similar to this? https://github.com/Ahsizara/cached_resource/issues/7

**Comment by jlurena** [comment]
Can this be closed? @mhgbrown

**Comment by mhgbrown** [comment]
Sure. Will wait for people to complain again 😃
