### ISSUE TITLE
user made to wait for caching to process

### ISSUE THREAD

**Issue by Daniel-ltw** [mhgbrown/cached_resource#26]
Currently, the user is made to wait for the caching mechanism to process it's write and read before things are returned. 
- lib/cached_resource/caching.rb:42..44

```
cache_collection_synchronize(object, *arguments) if cached_resource.collection_synchronize
cache_write(key, object)
cache_read(key)
```

Could we wrap that around a new thread, so that the thread would process the caching, but return the retrieve object after the thread have been spawn? 

This way, users need not waiting for the three lines of code to be process, this would reduce the response time by a great amount. This is especially so if collection_synchronize is true.

**Comment by Daniel-ltw** [comment]
Anyone else would like to contribute to this topic? 

From how I have seen this, the threading should work. 

A new thread is spawn and it is use to do write objects to the cache. 
Now one problem I can see is that the dog piling would create multiple thread which would try to do their write and the :race_condition_ttl should handle that nicely. 

Would like further input on this and would like to hear if I am actually missing anything here.

**Comment by mhgbrown** [comment]
Yeah, we should be careful with dog piling. The only thing I'm thinking about is how we create the threads. I haven't been doing a lot of Ruby recently, but is there some sort of thread pooling mechanism?

**Comment by Daniel-ltw** [comment]
With the above pull request, you could see the code changes. 

Currently, I am just concern what more needs and could be done.

**Comment by josh-h** [comment]
Your `join` call on the thread forces the thread to complete before the find method can return. Which results in the find method waiting for the write to finish before returning.

Another approach, if you are okay adding a dependency to 'concurrent-ruby' would be to calling cache_write with 'async'. What I like about that approach is each ActiveResource type gets its own thread for writing to the cache. Which will queue writes during dog piling as you were concerned earlier, but still lets the find return before the cache is written to disk.

**Comment by Daniel-ltw** [comment]
@josh-h I like that idea, but I do not have the capacity to work on this anymore. 
Would be happy to see a pull request from you and I would get that merge in. 

Not sure if we could actually get some test written for this as well.

**Comment by jlurena** [comment]
@mhgbrown this is a good idea. Any thoughts on continuing ? Granted this issue is almost 9 years old

**Comment by mhgbrown** [comment]
I am fully down and like what you proposed here. Do you want to give it a shot?

**Comment by giritdwiputra** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://bit.ly/48M0kd2)

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](http://bit.ly/48M0kd2) link.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in ETH!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with Binance!


Winners: @rbad, @evanjmg, @johnnymn, @OnyiaRichard, @Alexintosh, @dennisvandalen, @bmxer13

**Comment by jlurena** [comment]
After 6 years... Lol here we go: https://github.com/mhgbrown/cached_resource/pull/61 @mhgbrown 

I do need help with specs. @josh-h @Daniel-ltw if you guys could review or give suggestions on how to best write specs I'd appreciate it.

**Comment by mhgbrown** [comment]
Awesome, nice work @jlurena. I'm low on time for the next week and a bit, will give it a look when I can. re: specs, I'll also have to do some digging.

**Comment by jlurena** [comment]
@mhgbrown would it be possible for you to make me a maintainer?

**Comment by mhgbrown** [comment]
@jlurena you're in. lmk if your perms are in need of adjustment.

**Comment by jlurena** [comment]
I finished it. @mhgbrown pls CR https://github.com/mhgbrown/cached_resource/pull/61

**Comment by mhgbrown** [comment]
@jlurena thanks for your work. I've merged your PR and [there's a compat problem](https://github.com/mhgbrown/cached_resource/actions/runs/8959539163/job/24605062973) with ruby 1.9 and concurrent ruby:

```
    concurrent-ruby (>= 1.2.3, ~> 1.2) was resolved to 1.2.3, which depends on
      ruby (>= 2.3)
```

What do you think is the best course of action? Skip the tests and and installation of concurrent ruby for ruby < 2.3? Is Ruby < 2.3 still in wide enough use?

**Comment by jlurena** [comment]
Honestly, should stop supporting ruby 1.9 lol. It's been dead for years

**Comment by mhgbrown** [comment]
Ok, I'll get something going to remove the support.

**Comment by jlurena** [comment]
> Ok, I'll get something going to remove the support.

Yeah likely maybe anything under 2.3 should be removed. 2.3 has been EOL for 8 years and 1.9 for 12.

https://endoflife.date/ruby

**Comment by mhgbrown** [comment]
released: https://rubygems.org/gems/cached_resource/versions/8.0.0
