### ISSUE TITLE
Storing objects as json in cache breaks persistence

### ISSUE THREAD

**Issue by vibro** [mhgbrown/cached_resource#42]
I recently updated to 5.1.0 after experiencing the problems that #40 fixed. However, I tried updating an object I had retrieved from the cache, and the persistence field is missing. This means instead of calling update, ActiveResource called create on the object.

I tried calling find with reload => true, but it looks like it writes to the cache and then reads from there, causing the same problem. 

Old Behavior (5.0.1):
```2.3.1 :004 >   m = MyActiveResource.find('123')
Cache read: my_active_resource/123
Dalli::Server#connect 127.0.0.1:11211
Cache write: my_active_resource/123 ({:race_condition_ttl=>86400, :expires_in=>604800})
[cached_resource] WRITE my_active_resource/123
Cache read: my_active_resource/123
[cached_resource] READ my_active_resource/123
 => #<MyActiveResource:0x007fb59e0ba8c8 @attributes={"id"=>123}, @prefix_options={}, @persisted=true> 
2.3.1 :005 > m.persisted?
 => true 
```

New behavior:
```2.3.1 :001 > m = MyActiveResource.find('123')
Cache read: my_active_resource/123
Dalli::Server#connect 127.0.0.1:11211
Cache write: my_active_resource/123 ({:race_condition_ttl=>86400, :expires_in=>604800})
[cached_resource] WRITE my_active_resource/123
Cache read: my_active_resource/123
[cached_resource] READ my_active_resource/123
 => #<MyActiveResource:0x007fab706a1f58 @attributes={"id"=>123 }, @prefix_options={}, @persisted=false> 
2.3.1 :002 > m.persisted?
 => false 
```

Is there a way to keep persistence? Or stop reading directly from the cache in instances where I want to update?

**Comment by Daniel-ltw** [comment]
Could you debug this issue and try to also include the prefix_options and the persisted into the json?

**Comment by vibro** [comment]
I think I was able to solve it by adding persisted:

```# Write an entry to the cache for the given key and value.
def cache_write(key, object)
  if object.is_a? Enumerable
    json = object.map { |o| { object: o.to_json, persistence: o.persited? } }.to_json
  else
    json = { object: object.to_json, persistence: object.persited? }.to_json
  end
  result = cached_resource.cache.write(key, json, :race_condition_ttl => cached_resource.race_condition_ttl, :expires_in => cached_resource.generate_ttl)
  result && cached_resource.logger.info("#{CachedResource::Configuration::LOGGER_PREFIX} WRITE #{key}")
  result
end

def json_to_object(json)
  if json.is_a? Array
    json.map { |attrs| self.new(attrs[:object], attrs[:persistence]) }
  else
    self.new(json[:object], json[:persistence])
  end
end
```

If this is the right direction, happy to open a PR for it.

**Comment by Daniel-ltw** [comment]
Did the instantiation of the object work? 

That all looks like it is the right direction. 
Feel free to create a pull request.

**Comment by mhgbrown** [comment]
@Daniel-ltw 💪for being on top of this. I'll make a new release with https://github.com/mhgbrown/cached_resource/pull/43 soon.

**Comment by mhgbrown** [comment]
published in 5.1.1 https://rubygems.org/gems/cached_resource/versions/5.1.1

**Comment by Daniel-ltw** [comment]
@mhgbrown @vibro did all the work. 
Kudos to @vibro

**Comment by mhgbrown** [comment]
Absolutely. I just mean you acting as a "face" of cached_resource.

**Comment by Daniel-ltw** [comment]
Happy to help out a fellow developer as and when I can.

**Comment by vibro** [comment]
Thanks everyone!
