### ISSUE TITLE
NoMethodError if no record is found

### ISSUE THREAD

**Issue by csuma** [mhgbrown/cached_resource#45]
Hello.
ActiveRessource 5.1.0 has a breaking change. 
In 5.0.0 the find method with all, first and last scope returns an empty array if no resource is found. In 5.1.0 it returns `nil`, which leads to a `NoMethodError` in caching.rb, line 141. `nil` has no `persited?` method.

**Comment by Daniel-ltw** [comment]
Feel free to open a pull request. 

Will be keen to look at it.
