### ISSUE TITLE
clear_cache deletes everything

### ISSUE THREAD

**Issue by jvnill** [mhgbrown/cached_resource#48]
We are using redis as our cache store.  Using `clear_cache` deletes everything in redis, even sidekiq data.

**Comment by mhgbrown** [comment]
What happens when you call the underlying cache clear method? Does it take options (e.g. as described [here](https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-clear)) to preserve the sidekiq data?

**Comment by jvnill** [comment]
yeah but the `clear_cache` method offered by this gem does not accept any parameters.  It should also be expected that when you do `Thing.clear_cache`, it would clear the cache for `Thing` **only**

**Comment by mhgbrown** [comment]
Ah I see, that makes total sense. I guess adding the `options` parameter is pretty trivial. As for deleting `Thing` only, it looks like https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-delete_matched would work. What do you think?

**Comment by jvnill** [comment]
yep I agree
