### ISSUE TITLE
Calls to where are not cached

### ISSUE THREAD

**Issue by sudoaza** [mhgbrown/cached_resource#52]
Looks like `find` calls are intercepted but not `where` calls. Is this by design?

**Comment by mhgbrown** [comment]
It might have just been overlooked! However, I see that `where` [uses `find` under the hood](https://github.com/rails/activeresource/blob/master/lib/active_resource/base.rb#L1045) and we alias [`find` with `find_with_cache`](https://github.com/mhgbrown/cached_resource/blob/master/lib/cached_resource/caching.rb#L10). Doesn't this cover `where` (I'm a little Ruby rusty these days)?

**Comment by sudoaza** [comment]
Ah that probably does it, I was overriding `where` but not `find` somewhere else and thought this would apply here too. Closing, thanks!
