### ISSUE TITLE
Improve local development environment

### ISSUE THREAD

**Issue by mhgbrown** [mhgbrown/cached_resource#54]
We're running into a problem where we need to start using different Ruby versions and different bundler versions to properly test all permutations locally. This is easy to configure with travis ci, but less so locally. No more does one Ruby version and one Bundler version suffice for all dependency options. For example:

- Rails 4 (or maybe a core dependency, I can't remember) requires bundler < 2
- Ruby 2.7.x won't run bundler:1.17.3

[A useful Ruby+Rails compatibility table](https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html)

**Comment by jlurena** [comment]
I think this was done. Can we close this? @mhgbrown

**Comment by mhgbrown** [comment]
Yes!
