### ISSUE TITLE
Chained calls do not work like it does in `active_resouce`

### ISSUE THREAD

**Issue by jlurena** [mhgbrown/cached_resource#57]
Example:

```
MyActiveResource.where(name: 'bob').where(last_name: 'the builder')
```

throws an error because the previous params `{ name: 'bob' }` is not assigned to the `original_params` https://github.com/rails/activeresource/blob/df28dee231f8573c18d9e091c7fd7bc6d6679263/lib/active_resource/base.rb#L1097 

I can also create PR if its agreed this should be fixed.

**Comment by mhgbrown** [comment]
I agree, go for it.

**Comment by jlurena** [comment]
Created PR: https://github.com/mhgbrown/cached_resource/pull/59 @mhgbrown

**Comment by jlurena** [comment]
Additional: https://github.com/mhgbrown/cached_resource/pull/60
