### ISSUE TITLE
Avoid cache nil or empty array responses

### ISSUE THREAD

**Issue by italijancic-th** [mhgbrown/cached_resource#62]
As the title said, I think we shouldn't cache `nil` or `[]` responses.

I can create a PR for this if you agree.

**Comment by mhgbrown** [comment]
I think that's great. Looks like you're already in progress. Let us know when the PR is ready for review.

**Comment by italijancic-th** [comment]
Perfect, the PR is ready for review. I will wait for your feedback on it 😉 !
