### ISSUE TITLE
Update rspecs and CI

### ISSUE THREAD

**Issue by jlurena** [mhgbrown/cached_resource#68]
RSpecs are using old DSL/syntax
- Add coverage
- Update Github CI to run on pull requests
- Add linter (recommend [standardrb](https://github.com/standardrb/standard) thoughts @mhgbrown ?)

**Comment by mhgbrown** [comment]
I think [standardrb](https://github.com/standardrb/standard) is great

**Comment by jlurena** [comment]
This was done.
